"""Poseidon over the BN254 scalar field, matching circomlib (P5.2).

The commitment `C` (P5.3) is a Poseidon hash, and the Circom circuit in P7.5
recomputes it with circomlib's ``Poseidon`` template. The host side therefore
has to produce exactly circomlib's output, field element for field element.
This module is that host side. It is stdlib only.

Why written here and not pip-installed
--------------------------------------
"Poseidon" is a family: the field, the width, the round numbers, the round
constants, the MDS matrix and the way inputs are placed in the state all vary
between libraries, and two correct implementations of different instances
never agree. The only instance that matters here is circomlib's. A short
implementation that is checked against circomlib's own JavaScript
(`circomlibjs`) is easier to trust than a third-party package whose instance
has to be established anyway. The check is `tests/test_poseidon.py` and
`experiments/p5_2_validate_poseidon.py`.

The instance
------------
- **Field:** the BN254 (alt_bn128) scalar field, ``p =
  21888242871839275222246405745257275088548364400416034343698204186575808495617``.
- **S-box:** ``x^5``.
- **Width:** ``t = n + 1`` for ``n`` inputs, ``1 <= n <= 16``.
- **Rounds:** ``R_F = 8`` full rounds and ``R_P`` partial rounds, with ``R_P``
  = 56, 57, 56, 60, 60, 63, 64, 63, 60, 66, 60, 65, 70, 60, 64, 68 for
  ``t`` = 2 … 17.
- **Round constants and MDS matrix:** generated by the Grain LFSR of the
  Poseidon reference implementation (``generate_parameters_grain.sage``),
  re-implemented in `grain_parameters`. Nothing is copied in as a table: the
  constants are derived from ``(p, t, R_F, R_P)`` alone, and the test vectors
  check the derivation. The MDS matrix is the first Cauchy matrix the
  generator yields; the reference script's extra security filters are not
  re-implemented, and agreement with circomlibjs at every width shows the
  first matrix is the one circomlib uses.
- **Hash:** the state starts as ``[0, x_1, …, x_n]``, the permutation is
  applied once, and the output is state element 0.

Each round adds the round constants, applies the S-box (to every element in a
full round, to element 0 only in a partial round) and multiplies by the MDS
matrix. The order is 4 full rounds, ``R_P`` partial rounds, 4 full rounds.
circomlib's circuit uses an optimized but equivalent form of the same
permutation.

Inputs
------
Inputs are Python ints in ``[0, p)``. Anything else is refused: an int outside
the field is **not** reduced silently, because two different inputs that
reduce to the same element would hash alike, and a commitment must not allow
that. How `K`, `S` and the nonce become field elements is P5.3.

Not constant time. Python big-int arithmetic leaks timing, so do not hash
secrets with this where an attacker can time it. Here it runs on the owner's
own machine.
"""

from __future__ import annotations

from functools import lru_cache

BN254_SCALAR_FIELD = 21888242871839275222246405745257275088548364400416034343698204186575808495617
"""Order of the BN254 scalar field, the field circom works in by default."""

FIELD_BITS = 254
FULL_ROUNDS = 8
PARTIAL_ROUNDS = (56, 57, 56, 60, 60, 63, 64, 63, 60, 66, 60, 65, 70, 60, 64, 68)
"""circomlib's partial round counts for widths t = 2 … 17."""
MAX_INPUTS = len(PARTIAL_ROUNDS)
SBOX_EXPONENT = 5
POSEIDON_INSTANCE = "poseidon/bn254/x5/circomlib"

_P = BN254_SCALAR_FIELD


def partial_rounds(t: int) -> int:
    """R_P for state width `t`."""
    if isinstance(t, bool) or not isinstance(t, int) or not 2 <= t <= MAX_INPUTS + 1:
        raise ValueError(f"width t must be an int in [2, {MAX_INPUTS + 1}], got {t!r}")
    return PARTIAL_ROUNDS[t - 2]


class _Grain:
    """The 80-bit Grain LFSR in self-shrinking mode, as the Poseidon reference script uses it."""

    def __init__(self, t: int, full_rounds: int, partial: int) -> None:
        def bits(value: int, width: int) -> list[int]:
            return [(value >> (width - 1 - i)) & 1 for i in range(width)]

        # field type 1 (prime), S-box 0 (x^alpha), field size, t, R_F, R_P, then thirty 1 bits
        self._state = (bits(1, 2) + bits(0, 4) + bits(FIELD_BITS, 12) + bits(t, 12)
                       + bits(full_rounds, 10) + bits(partial, 10) + [1] * 30)
        self._head = 0
        for _ in range(160):
            self._update()

    def _update(self) -> int:
        s, h = self._state, self._head
        new = s[h + 62] ^ s[h + 51] ^ s[h + 38] ^ s[h + 23] ^ s[h + 13] ^ s[h]
        s.append(new)
        self._head = h + 1
        if self._head > 4096:  # drop consumed bits
            del s[: self._head]
            self._head = 0
        return new

    def bit(self) -> int:
        # A bit is kept only if the bit before it is 1.
        while self._update() == 0:
            self._update()
        return self._update()

    def integer(self, bits: int = FIELD_BITS) -> int:
        value = 0
        for _ in range(bits):
            value = (value << 1) | self.bit()
        return value


@lru_cache(maxsize=None)
def grain_parameters(t: int) -> tuple[tuple[int, ...], tuple[tuple[int, ...], ...]]:
    """Round constants and MDS matrix for width `t`.

    Returns ``(constants, mds)``. ``constants`` has ``(R_F + R_P) * t`` field
    elements, round by round. ``mds[i][j]`` is the Cauchy matrix
    ``1 / (x_i + y_j)``.
    """
    rounds = FULL_ROUNDS + partial_rounds(t)
    grain = _Grain(t, FULL_ROUNDS, partial_rounds(t))

    constants = []
    while len(constants) < rounds * t:
        candidate = grain.integer()
        if candidate < _P:  # rejection sampling: uniform over the field
            constants.append(candidate)

    while True:
        points = [grain.integer() % _P for _ in range(2 * t)]
        if len(set(points)) != 2 * t:
            continue
        xs, ys = points[:t], points[t:]
        if any((x + y) % _P == 0 for x in xs for y in ys):
            continue
        mds = tuple(tuple(pow(x + y, -1, _P) for y in ys) for x in xs)
        return tuple(constants), mds


def poseidon_permutation(state: list[int] | tuple[int, ...]) -> list[int]:
    """Apply the Poseidon permutation to a full state of ``t`` field elements."""
    state = [_element(x, f"state[{i}]") for i, x in enumerate(state)]
    t = len(state)
    constants, mds = grain_parameters(t)
    partial = partial_rounds(t)
    half = FULL_ROUNDS // 2
    for r in range(FULL_ROUNDS + partial):
        state = [(x + c) % _P for x, c in zip(state, constants[r * t:(r + 1) * t])]
        if r < half or r >= half + partial:
            state = [pow(x, SBOX_EXPONENT, _P) for x in state]
        else:
            state[0] = pow(state[0], SBOX_EXPONENT, _P)
        state = [sum(m * x for m, x in zip(row, state)) % _P for row in mds]
    return state


def poseidon(inputs: list[int] | tuple[int, ...]) -> int:
    """circomlib's ``Poseidon(n)``: hash 1 to 16 field elements to one field element."""
    if not isinstance(inputs, (list, tuple)):
        raise TypeError(f"inputs must be a list or tuple of ints, got {type(inputs).__name__}")
    if not 1 <= len(inputs) <= MAX_INPUTS:
        raise ValueError(f"Poseidon takes 1 to {MAX_INPUTS} inputs, got {len(inputs)}")
    return poseidon_permutation([0, *inputs])[0]


def _element(value, name: str) -> int:
    if isinstance(value, bool) or not isinstance(value, int):
        raise TypeError(f"{name} must be an int, got {type(value).__name__}")
    if not 0 <= value < _P:
        raise ValueError(f"{name} is outside the field [0, p); reduce or split it explicitly first")
    return value
